### ISSUE TITLE
TM/Eitm: launcher icons are tiny compared to normal tm, see screenshots

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#25]
launcher iconsize in tm
![li-tm](https://cloud.githubusercontent.com/assets/840070/5126075/56736c76-70ca-11e4-8623-d932c8f4389c.png)
launcher iconsize in eitm
![li-eitm](https://cloud.githubusercontent.com/assets/840070/5126073/53441cb2-70ca-11e4-859e-becedbc07e89.png)

**Comment by star-buck** [comment]
this is now again tiny with KCI 20150109, but this time
- with breeze default theme
- in normal TM
![tm-iconsize](https://cloud.githubusercontent.com/assets/840070/5692682/30ddd188-98ff-11e4-8c6b-98d4e9b69a36.png)

**Comment by star-buck** [comment]
this affects various plasma themes, like GnomeShell theme, etc., 
maybe its possible to interpret the size and padding of launcher icons the same as the normal panel icons (Terminal, Lbreoffice in above screenshot) like kde4.x?

**Comment by eikehein** [comment]
Can't seem to reproduce it right now on Fedora, I'll have a look at the ISO on Monday. Annoying that there keep being problems with this, sorry. Not sure what it's this time, especially since the code doesn't really change ...

Regarding the question, right now the goal is that the icon size is the same as for a running task, so it doesn't change when you run it. It's true that this means it's different from an Icon applet, because the latter doesn't have to account for a frame theme element. This could be changed, but then the icon size would change from launcher to running. That's not *that* noticable with the normal Task Manager, but it would be fairly noticable in Icons-only Tasks, which uses 95% the same code, and more exceptions always mean a little more bug potential, so I'd be reluctant to change it.

As for 4.x vs 5: When I rewrote the Task Manager for 4.11, I improved the correctness of the task theming to properly account for the frame margin widths. The old C++ applet ignored them and hard-baked pixel values, which means themes got designed around the applet behavior instead of the other way around. This meant themes didn't have good control. Changing the behavior meant that some themes "broke" a little, but others work better now.

**Comment by star-buck** [comment]
icons staying the same size makes sense, also with regards to the shrinking issue...
i would think that breeze and TM are now CORRECT being so tiny then, breeze is also a new theme, so it shouldnt have a regression there?
Do you have a screenshot how breeze launchers look in fedora with same panel height?

**Comment by eikehein** [comment]
The Breeze theme is correct, yes. Basically, the launcher icons should be the same size as the running task icons. They aren't on your screenshot (well there is no running tasks on your shot, but I assume they're bigger because they should be), so there's a bug I need to fix.

**Comment by star-buck** [comment]
how about the screenshot from fedora to compare?

**Comment by eikehein** [comment]
http://i.imgur.com/fR7smZg.png

**Comment by eikehein** [comment]
^ Note the icons are really the same size, but Mozilla's circle is a bit smaller because they have a bigger shadow in the graphic.

**Comment by star-buck** [comment]
somehow its a bit frightening that they dont look like the fedora with latest ISO... either its a themeing issue or maybe it didnt get applied correctly...? like if you change themes via system settings, the new themes are not correctly applied at first, and i like to make a claim that somehow even after relogin, some parts stay odd, like some edge-curves around the menu for example, depending on what theme and state was loaded before you changed to the actual theme... was definetely better working under kde4, so who is maintaining the whole plasma desktop themeing settings and engine?

**Comment by eikehein** [comment]
Marco has done the most work on it and is the de-facto maintainer, but all of the Plasma hackers are pretty much responsible for it together.

I don't think this is a theming bug though, because the theme element in the launcher and the running task is the same, so it doesn't make sense that it would be different from one to the other. That is, even if theming behaved differently on Fedora from Kubuntu, theming probably can't explain why it breaks on Kubuntu. This is most likely just some subtle chaos in the Task Manager's layout engine I need to clean up. I can't account for the behavior difference between the systems without investigating it, but one possibility is that it could be related to font metrics (which it should not be, which would then be the bug).

**Comment by eikehein** [comment]
OK, sat down and cleaned up the code some more.

TM+ITM: http://commits.kde.org/plasma-desktop/d04ca3eafab9bff94196bed42eb84d962e58a8f1
EITM: http://commits.kde.org/scratch/hein/expanding-icons-taskmanager/744efca7c48d4d66dc1cdd3b6e2d1b11d6b2eb86

Same codepath in all cases now, which should put this to bed.

**Comment by eikehein** [comment]
package: plasma-desktop
fixed: Sat 10th
target ISO: Fri 16th
qa method: add a launcher to the Task Manager, icon size should match buttons of running tasks

**Comment by star-buck** [comment]
icon size now omly seems related to wrong margins in theme 
(example: Gnome-Shell now looks way different (unusuable) comaprted to kde4.x)

**Comment by eikehein** [comment]
The Gnome-Shell-KDE theme has a massive margin in panel.svgz which is 100% a theme bug. It's possible that KDE 4 ignored this margin so that the bug wasn't visible before. Very easy to see though: Open panel.svgz with Inkscape and see how huge the top border element is.
