### ISSUE TITLE
[missing translations]: needs packaging of language packs

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#41]
language selection kcm is empty

**Comment by star-buck** [comment]
Somehow kaos seems to provide langauge to choose from in that kcm:
https://forum.manjaro.org/index.php?topic=18150.msg177936#msg177936
Is that a package problem of KCI or how did Kaos manage to do this?

**Comment by apachelogger** [comment]
https://github.com/blue-systems/plasma-5.2/issues/41#issuecomment-66595398

the options are:
- use KCI plasma which doesn't have translations
- use 5.2.0 release packages which has translations and is what is in KCI anyway

for frameworks the same applies, alas, going with frameworks 5.6 means not having the 5.7 fixes, so I would use KCI frameworks and possibly update to 5.7 when released to get translations.

the good news is that I recently improved the plasma release script to allow us to possibly use it for tarball creation so that CI builds will get translation support in the future. whenever that gets finalized.

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-52

This PPA needs the official Qt 5.4 backports to work
https://launchpad.net/~kubuntu-ppa/+archive/ubuntu/utopic-qt54 

Once I have the go-ahead to put plasma 5.2.0 in ci-stable, I'll also copy the Qt backport over.
